package main

import (
	"fmt"
	"github.com/Abiji-2020/NexOrb/config"
	_ "github.com/Abiji-2020/NexOrb/docs" // docs is generated by Swag CLI
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
)

// @title NexOrb API
// @version 1.0
// @description This is the API documentation for NexOrb.
// @host localhost:8080
// @BasePath /v1/api

func main() {
	app := config.NewConfig()
	if app == nil {
		fmt.Println("Error initializing the app")
		return
	}
	app.InitializeRoutes()
	app.Logger.LogInfo("Routes initialized")

	app.Logger.LogInfo("Migrating the database")
	err := app.MigrateDatabase()
	if err != nil {
		app.Logger.LogError(fmt.Sprintf("Error migrating the database: %v", err))
		return
	}

	// Set up Swagger route
	app.Router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start the Gin server
	err = app.Router.Run(":" + app.ServerPort)
	if err != nil {
		app.Logger.LogFatal("Failed to start server: " + err.Error())
	}

	app.Logger.LogInfo("Server started on port " + app.ServerPort)
}
